# Site settings
name: 志恒识
email: 491823689@qq.com
author: 志恒识
url: ''
resume_site: ''
github: https://github.com/lizanle521/
baseurl: ""
description: 有志，则不甘下流；有恒，则无不成之事；有识，则不敢骄矜；
meta_description: 李赞乐;个人博客;有志有恒有识;lizanle521;lizanle;java;
banner: 有志，则不甘下流；有恒，则无不成之事；有识，则不敢骄矜；

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: lizanle521

# Build settings
markdown: kramdown

